#include "aiop_verification.h"

/* Address of the stack as generated by the linker */
extern const uint16_t _stack_addr[];

asm void init_stack_ptr(void);

asm void init_stack_ptr(void)
{
	e_lis    rsp, _stack_addr@ha
	e_add16i rsp, rsp, _stack_addr@l
	blr
}

#define __wait()	asm ("wait  \n"	)

int main()
{	
	__wait();
/* initialize stack pointer */
	init_stack_ptr();
	aiop_verification();
	aiop_verification_fm();
	
	return 0;
}
