#include "aiop_verification.h"

/* Address of the stack as generated by the linker */
extern const uint16_t _stack_addr[];


#define __wait()	asm ("wait  \n"	)

int main()
{	
	__wait();
/* initialize stack pointer */
#pragma suppress_warnings on
	asm {
		e_lis    rsp, _stack_addr@ha
		e_add16i rsp, rsp, _stack_addr@l
	}
#pragma suppress_warnings off
	
	aiop_verification();
	aiop_verification_fm();
	
	return 0;
}
