#ifndef __APPS_ARCH_H
#define __APPS_ARCH_H

#define ARCH_DP_DDR_SIZE	(128 * MEGABYTE)
#define ARCH_SYS_DDR_SIZE	(4 * MEGABYTE)
#define ARCH_CTLU_DP_DDR_NUM_ENTRIES (2048)
#define ARCH_MFLU_DP_DDR_NUM_ENTRIES (2048)


#endif /* __APPS_ARCH_H */
